import express from 'express';
import cors from 'cors';
import cookieParser from 'cookie-parser';
import mongoose from 'mongoose';
import { config } from './config.js';
import authRoutes from './routes/auth.js';
import orderRoutes from './routes/orders.js';
import adminRoutes from './routes/admin.js';
import addressRoutes from './routes/addresses.js';
import cartRoutes from './routes/cart.js';
import productRoutes, { adminProductRoutes } from './routes/products.js';
import checkoutRoutes from './routes/checkout.js';
import uploadRoutes from './routes/uploads.js';
import profileRoutes from './routes/profile.js';
import wishlistRoutes from './routes/wishlist.js';
import webhookRoutes from './routes/webhooks.js';
import { ensureDefaultCategories } from './categories.js';
import { Address, Order, WebhookEvent, WishlistItem } from './models.js';

await mongoose.connect(config.mongoUri, { serverSelectionTimeoutMS: 10000 });
await Promise.all([Address.createIndexes(), Order.createIndexes(), WishlistItem.createIndexes(), WebhookEvent.createIndexes()]);
await ensureDefaultCategories();
const app = express();
app.disable('x-powered-by');
app.use((_request, response, next) => {
  response.setHeader('Content-Security-Policy', "default-src 'self'; base-uri 'self'; object-src 'none'; frame-ancestors 'none'; script-src 'self' 'unsafe-inline' https://checkout.razorpay.com https://accounts.google.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:; img-src 'self' data: blob: https://res.cloudinary.com; connect-src 'self' https://accounts.google.com; frame-src https://api.razorpay.com https://checkout.razorpay.com https://accounts.google.com; form-action 'self'");
  response.setHeader('X-Content-Type-Options', 'nosniff'); response.setHeader('X-Frame-Options', 'DENY'); response.setHeader('Referrer-Policy', 'strict-origin-when-cross-origin'); response.setHeader('Permissions-Policy', 'camera=(), microphone=(), geolocation=(), payment=(self)');
  if (config.isProduction) response.setHeader('Strict-Transport-Security', 'max-age=31536000; includeSubDomains');
  next();
});
app.use(cors({ origin: (origin, callback) => callback(null, !origin || config.frontendOrigins.includes(origin)), credentials: true }));
app.use('/api/webhooks', express.raw({ type: 'application/json', limit: '1mb' }), webhookRoutes);
app.use(express.json({ limit: '1mb' }));
app.use(cookieParser());
app.get('/health', (_request, response) => response.json({ ok: true }));
app.use('/api/auth', authRoutes);
app.use('/api/profile', profileRoutes);
app.use('/api/wishlist', wishlistRoutes);
app.use('/api/orders', orderRoutes);
app.use('/api/admin', adminRoutes);
app.use('/api/addresses', addressRoutes);
app.use('/api/cart', cartRoutes);
app.use('/api/products', productRoutes);
app.use('/api/admin', adminProductRoutes);
app.use('/api/checkout', checkoutRoutes);
app.use('/api/admin/uploads', uploadRoutes);
app.use((error, _request, response, _next) => {
  const isInvalidJson = error instanceof SyntaxError && error.status === 400 && Object.prototype.hasOwnProperty.call(error, 'body');
  console.error(error?.name || 'Unhandled server error');
  const status = error?.name === 'ZodError' || isInvalidJson ? 400 : 500;
  response.status(status).json({ success: false, error: status === 400 ? 'Invalid request data' : 'Something went wrong' });
});
app.listen(config.port, () => console.log(`Jannat API listening on ${config.port}`));
